version: '3'
networks:
  default:
    external: true
    name: matrinos-network

volumes:
  liftbridge-data1:
  liftbridge-data2:
  liftbridge-data3:

services:
  natsboard:
    build:
      context: .
      dockerfile: Dockerfile.natsboard
    ports:
      - "3000:3000"
    command: '/wait-for.sh natsboard --nats-mon-url http://nats:8222'
    environment:
      - WAIT_FOR_HOST=mainflux-nats
      - WAIT_FOR_PORT=8222
  liftbridge1:
    build:
      context: ../../
      dockerfile: docker/dev-cluster/Dockerfile.compose
    ports:
      - "9292:9292"
    command: [
      '/wait-for.sh',
      '/liftbridge',
      '--data-dir=/data1',
      '--port=9292',
      '--level=debug',
      '--nats-servers=mainflux-nats:4222',
      '--raft-bootstrap-seed',
      '--id=server-1'
    ]
    environment:
      - WAIT_FOR_HOST=mainflux-nats
      - WAIT_FOR_PORT=4222
    volumes:
      - liftbridge-data1:/data1
  liftbridge2:
    build:
      context: ../../
      dockerfile: docker/dev-cluster/Dockerfile.compose
    ports:
      - "9293:9293"
    command: [
      '/wait-for.sh',
      '/liftbridge',
      '--data-dir=/data2',
      '--port=9293',
      '--level=debug',
      '--nats-servers=mainflux-nats:4222',
      '--id=server-2'
    ]
    environment:
      - WAIT_FOR_HOST=mainflux-nats
      - WAIT_FOR_PORT=4222
    volumes:
      - liftbridge-data2:/data2
  liftbridge3:
    build:
      context: ../../
      dockerfile: docker/dev-cluster/Dockerfile.compose
    ports:
      - "9294:9294"
    command: [
      '/wait-for.sh',
      '/liftbridge',
      '--data-dir=/data3',
      '--port=9294',
      '--level=debug',
      '--nats-servers=mainflux-nats:4222',
      '--id=server-3'
    ]
    environment:
      - WAIT_FOR_HOST=mainflux-nats
      - WAIT_FOR_PORT=4222
    volumes:
      - liftbridge-data3:/data3